name: ela-env
dependencies:
- python=2.7
- numpy
- pandas
- imgurpython
- Pillow
- scipy
- imread
- sklearn
- matplotlib
- scikit-image
- xgboost
- tensorflow
- np_utils
- keras
- jupyternotify
- opencv-python
